apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql

spec:
  serviceName: postgresql
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
      - name: postgresql
        image: postgres:15
        envFrom:
          - configMapRef:
              name: postgresql-conf
          - secretRef:
              name: postgresql-secret
        ports:
        - containerPort: {{ .Values.postgresql.containerPort }}
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "100m"
        volumeMounts:
        - name: postgresql-data
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: postgresql-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql
  labels:
    app: postgresql
spec:
  ports:
  - port: {{ .Values.postgresql.containerPort }}
    targetPort: {{ .Values.postgresql.containerPort }}
  selector:
    app: postgresql
  clusterIP: None
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-conf
data:
  POSTGRES_USER: {{ .Values.postgresql.auth.username }}
  # POSTGRES_PASSWORD: {{ .Values.postgresql.auth.password }}
  POSTGRES_DB: {{ .Values.postgresql.auth.database }}

--- 

apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: sausage-backend-report
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/version: "{{ .Chart.AppVersion }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app.kubernetes.io/component: backend-report
    app.kubernetes.io/part-of: sausage-store
    env: "{{ .Values.global.environment }}"
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.postgresql.auth.password }}
