-- migrations/V001__create_tables.sql

DROP TABLE IF EXISTS product;
DROP TABLE IF EXISTS product_info;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS orders_date;
DROP TABLE IF EXISTS order_product;

CREATE TABLE product (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    picture_url VARCHAR(255)
);

CREATE TABLE product_info (
    product_id BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    price DOUBLE PRECISION,
    FOREIGN KEY (product_id) REFERENCES product(id) ON DELETE CASCADE
);

CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status VARCHAR(255)
);

CREATE TABLE orders_date (
    order_id BIGINT NOT NULL,
    status VARCHAR(255),
    date_created DATE DEFAULT CURRENT_DATE,
    FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE
);

CREATE TABLE order_product (
    quantity INTEGER NOT NULL,
    order_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
    FOREIGN KEY (product_id) REFERENCES product(id) ON DELETE CASCADE
);

-- Создание индексов для оптимизации бд
CREATE INDEX idx_product_info_product_id ON product_info(product_id);
CREATE INDEX idx_orders_date_order_id ON orders_date(order_id);
CREATE INDEX idx_order_product_order_id ON order_product(order_id);
CREATE INDEX idx_order_product_product_id ON order_product(product_id);